name: secrets
'on':
  push:
    branches:
      - fix/env-warning
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build index.js
        run: ./update-dist.sh
      - name: Commit dist/index.js
        run: |
          git add ./dist/index.js
          git commit -m "build index.js"
          git push