name: secrets-action
'on':
  push:
    branches:
      - fix/env-warning
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build index.js
        run: |
          npm i @vercel/ncc
          npx ncc build index.js
      - name: Commit dist/index.js
        - uses: actions/checkout@v2
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
        - run: |
            git add ./dist/index.js
            git commit -m "build index.js"
            git push