name: secrets
'on':
  push:
    branches:
      - fix/env-warning
jobs:
  main:
    steps:
      - name: Get credentials
        uses: leanix/secrets-action@fix/env-warning
        with:
          secret-store-credentials: '${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}'